remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Koty!]
description: [Koty to super zwierzęta]
logo: ![Logo](https://imgs.search.brave.com/V_KdBIOn0mnzjZ3BIO5j_8DoY6RkAhfHHmrKCKuyeQg/rs:fit:560:315:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC84Mi9jNi83ZS84/MmM2N2VlNTViMzll/MGMyMzA1YTc0NjFm/NjZjMjQxZS5qcGc)
